**TASK - 1**

Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [10]:
import pandas as pd
import numpy as np

In [19]:
d = np.random.rand(4, 4)
c = ['Feature1', 'Feature2', 'Feature3', 'Feature4']
i = ['Observation1', 'Observation2', 'Observation3', 'Observation4']
df = pd.DataFrame(d, columns=c, index=i)
df

              Feature1  Feature2  Feature3  Feature4
Observation1  0.647115  0.512330  0.840416  0.571204
Observation2  0.319401  0.559966  0.072244  0.062541
Observation3  0.395512  0.502689  0.519714  0.537514
Observation4  0.268732  0.524239  0.905722  0.191391

**TASK - 2**

Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [20]:
new_column_names = {
    'Feature1': 'Random value 1',
    'Feature2': 'Random value 2',
    'Feature3': 'Random value 3',
    'Feature4': 'Random value 4'
}
df.rename(columns=new_column_names, inplace=True)
df

              Random value 1  Random value 2  Random value 3  Random value 4
Observation1        0.647115        0.512330        0.840416        0.571204
Observation2        0.319401        0.559966        0.072244        0.062541
Observation3        0.395512        0.502689        0.519714        0.537514
Observation4        0.268732        0.524239        0.905722        0.191391

**TASK -3**

Find the descriptive statistics of the 'df' dataframe.

In [21]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.407690        0.524806        0.584524        0.340663
std          0.167906        0.025043        0.380911        0.252675
min          0.268732        0.502689        0.072244        0.062541
25%          0.306734        0.509920        0.407847        0.159178
50%          0.357457        0.518284        0.680065        0.364452
75%          0.458413        0.533170        0.856742        0.545937
max          0.647115        0.559966        0.905722        0.571204

**TASK - 4**

Check for the null values in 'df' and find the data type of the columns.

In [22]:
df.isnull()

              Random value 1  Random value 2  Random value 3  Random value 4
Observation1           False           False           False           False
Observation2           False           False           False           False
Observation3           False           False           False           False
Observation4           False           False           False           False

In [23]:
df.dtypes

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

**TASK - 5**

Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [24]:
#Using Location Method
df.loc[:, ['Random value 2', 'Random value 3']]

              Random value 2  Random value 3
Observation1        0.512330        0.840416
Observation2        0.559966        0.072244
Observation3        0.502689        0.519714
Observation4        0.524239        0.905722

In [25]:
#Using Index Location Method
df.iloc[:, [1, 2]]

              Random value 2  Random value 3
Observation1        0.512330        0.840416
Observation2        0.559966        0.072244
Observation3        0.502689        0.519714
Observation4        0.524239        0.905722